require 'rails_helper'

RSpec.describe "Request endpoints" do
  describe "Ai requests endpoint" do
    it "returns a list of technologies generated by the openai api", :vcr do

      data = {
        "needs": {
          "blind": {
            "tech_needs": ["screen readers"],
            "disability_description": ["are totaly blind and cannot use a mouse"]
          }
        }
      }
      
      post "/api/v1/ai_requests", params: data, as: :json

      expect(response).to be_successful

      result = JSON.parse(response.body, symbolize_names: true)

    end
  end
end